#!/usr/bin/env python3

import subprocess

# enable services
subprocess.run(["systemctl", "enable", "pd-webgui"],
  stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

subprocess.run(["systemctl", "start", "pd-webgui"],
  stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
